# 项目配置
spring:
  # 选择配置文件
  profiles:
    # dev 开发环境 | test 测试环境 | prod 线上环境
    active: dev
  # 应用名称
  application:
    name: project-shiro-redis-base-demo
  # 配置文件上传大小限制
  servlet:
    multipart:
      enabled: true
      # 单个文件上传最大限制
      max-file-size: 100MB
      # 单次请求文件上传最大限制
      max-request-size: 100MB
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.rain.shiro.project.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*.xml
  # 配置
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: simple
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 接口文档
knife4j:
  enable: true
  production: false
  basic:
    enable: true
    username: test
    password: 123
  openapi:
    title: ${spring.application.name}接口文档
    description: "暂无"
    concat: "-"
    version: "v1.0.0"
    group:
      all:
        group-name: all-api
        api-rule: package
        api-rule-resources: com.rain